// rpc package provides the proto files needed for inter-process messaging
//
// Code in this package is autogenerated through protoc.
// We use gogoprotobuf for faster marshalling and unmarshalling.
package rpc
